import { SPLIT_PROMPT_TEMPLATE } from '../../Editor/commentUtils'
import type { PromptPreset } from '../../shared/PromptActionConfig/presetTypes'

export const SPLIT_PRESETS: PromptPreset[] = [
  {
    name: '',
    label: 'Restructure into sections',
    hint: 'default · group into ## cells',
    prompt: SPLIT_PROMPT_TEMPLATE,
  },
  {
    name: 'cells',
    label: 'Split into fine cells',
    hint: 'finer per-topic cells',
    prompt: [
      `You are splitting a Pathly skill file into fine-grained, per-topic cells.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Identify every distinct topic, rule, or instruction and give each its own ## section.`,
      `Aim for cells of 3–10 lines each — small enough to edit independently in the skill editor.`,
      ``,
      `Rules:`,
      `- Preserve all existing content exactly — do not rewrite, add, or remove instructions`,
      `- Preserve every character byte-for-byte, including Unicode punctuation (em-dash —, en-dash –,`,
      `  curly quotes ' ' " ", ellipsis …). Never substitute or re-encode them.`,
      `- Every ## heading must be unique and 3–6 words`,
      `- Maintain the original logical order`,
      ``,
      `Write the restructured content to: {{FILE}}.split.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'tighten',
    label: 'Condense prose',
    hint: 'tighten without losing meaning',
    prompt: [
      `You are condensing a Pathly skill file to reduce verbosity without losing any meaning.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Rewrite each paragraph or rule to be as concise as possible. Remove filler words, merge`,
      `redundant sentences, and shorten examples — but never drop a distinct instruction or constraint.`,
      ``,
      `Rules:`,
      `- Every original instruction or constraint must survive — compress, do not delete`,
      `- Preserve every character byte-for-byte in headings and code blocks`,
      `- Preserve Unicode punctuation (em-dash —, en-dash –, curly quotes ' ' " ", ellipsis …).`,
      `  Never substitute or re-encode them.`,
      `- Keep the existing ## structure; do not add or remove sections`,
      ``,
      `Write the condensed content to: {{FILE}}.split.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'headings',
    label: 'Normalize headings',
    hint: 'normalize heading hierarchy',
    prompt: [
      `You are normalizing the heading hierarchy of a Pathly skill file.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Ensure the file uses a consistent ## / ### heading hierarchy:`,
      `- Top-level sections use ## (H2)`,
      `- Sub-sections use ### (H3); avoid H4+ unless strictly necessary`,
      `- Headings are title-cased and 3–6 words`,
      `- Duplicate headings are disambiguated with a suffix`,
      ``,
      `Rules:`,
      `- Preserve all body text exactly — only heading levels and wording may change`,
      `- Preserve every character byte-for-byte in body text, including Unicode punctuation`,
      `  (em-dash —, en-dash –, curly quotes ' ' " ", ellipsis …). Never substitute or re-encode them.`,
      `- Maintain the original logical order`,
      ``,
      `Write the normalized content to: {{FILE}}.split.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
]

// ── Multi-Analysis feature ──
// Every lens APPENDS one report entry to the array sidecar at {{SIDECAR}} (the diagram model),
// so lenses and repeat runs accumulate side-by-side instead of clobbering a single `.analysis`
// file. {{FILE}} and {{SIDECAR}} are resolved at spawn time by resolvePrompt().

/** Shared tail every analyze lens ends with — defines the append contract. */
function appendContract(lens: string, title: string): string {
  return [
    ``,
    `Append exactly ONE JSON object to the "analyses" array at {{SIDECAR}} (create the file with`,
    `{ "version": 1, "source": "{{FILE}}", "analyses": [] } if it does not exist).`,
    `The object must have these fields:`,
    `  "id":        "an_" followed by 5 random lowercase letters/digits`,
    `  "lens":      "${lens}"`,
    `  "title":     "${title}"`,
    `  "content":   the FULL markdown report (every section above) as a single JSON string`,
    `  "engine":    the name of the CLI you are running as (e.g. "claude")`,
    `  "model":     null`,
    `  "createdAt": the current date-time as an ISO-8601 string`,
    `Produce STRICTLY VALID JSON — escape the markdown for the "content" string (newlines as \\n,`,
    `double-quotes as \\", backslashes as \\\\). Do not modify or remove any existing entry.`,
    `Write {{SIDECAR}} as UTF-8 with your native file-writing tool — never via shell redirection`,
    `(Get-Content/Set-Content/Out-File or >), which corrupts Unicode on Windows.`,
    `Do not write any other file. Exit when done.`,
  ].join('\n')
}

/** Compose a lens prompt: intro → read file + sidecar → report spec → append contract. */
function buildLensPrompt(lens: string, title: string, intro: string, reportSpec: string[]): string {
  return [
    intro,
    ``,
    `Read the file at: {{FILE}}`,
    `Read the existing analysis sidecar (if any) at: {{SIDECAR}}`,
    ``,
    `Produce a markdown report with these sections:`,
    ``,
    ...reportSpec,
    appendContract(lens, title),
  ].join('\n')
}

export const ANALYZE_LENSES: PromptPreset[] = [
  {
    name: '',
    label: 'Full quality review',
    hint: 'default · strengths, gaps, redundancy',
    prompt: buildLensPrompt(
      'full',
      'Full quality review',
      'You are reviewing a Pathly skill file for overall quality.',
      [
        `## Summary`,
        `1–2 sentence overview of what this skill does.`,
        ``,
        `## Strengths`,
        `What this skill does well — clear instructions, good structure, appropriate scope.`,
        ``,
        `## Gaps & Ambiguities`,
        `Unclear instructions, missing edge cases, or steps that could be misinterpreted.`,
        `Reference exact phrases or sections where possible.`,
        ``,
        `## Redundancies`,
        `Verbose or repeated sections that could be tightened without losing meaning.`,
        ``,
        `## Suggested Improvements`,
        `Concrete, actionable changes ranked by impact. 1–2 sentences each.`,
        ``,
        `## Token Estimate`,
        `Rough token cost per invocation and whether it is appropriate for the task complexity.`,
      ],
    ),
  },
  {
    name: 'clarity',
    label: 'Clarity audit',
    hint: 'ambiguity / misread risks',
    prompt: buildLensPrompt(
      'clarity',
      'Clarity audit',
      'You are auditing a Pathly skill file for clarity and misread risks.',
      [
        `## Summary`,
        `1–2 sentence overview of what this skill does.`,
        ``,
        `## Ambiguous Instructions`,
        `Phrases or rules that an agent could misinterpret. Quote the exact text and explain the risk.`,
        ``,
        `## Implicit Assumptions`,
        `Things the skill assumes without stating — prior knowledge, context, or tool availability.`,
        ``,
        `## Suggested Rewrites`,
        `Concrete, drop-in rewrites for the most ambiguous passages. 1–2 per finding.`,
      ],
    ),
  },
  {
    name: 'gaps',
    label: 'Completeness check',
    hint: 'completeness / missing edge cases',
    prompt: buildLensPrompt(
      'gaps',
      'Completeness check',
      'You are checking a Pathly skill file for completeness and missing edge cases.',
      [
        `## Summary`,
        `1–2 sentence overview of what this skill does.`,
        ``,
        `## Missing Edge Cases`,
        `Scenarios the skill does not handle. For each: describe the scenario and its likely impact.`,
        ``,
        `## Incomplete Instructions`,
        `Steps that are started but not fully specified — an agent would need to guess.`,
        `Reference exact phrases or sections where possible.`,
        ``,
        `## Suggested Additions`,
        `Concrete text or rules to add, ranked by impact. Keep each suggestion to 1–3 sentences.`,
      ],
    ),
  },
  {
    name: 'redundancy',
    label: 'Redundancy scan',
    hint: 'verbosity + token cost',
    prompt: buildLensPrompt(
      'redundancy',
      'Redundancy scan',
      'You are scanning a Pathly skill file for redundancy and token waste.',
      [
        `## Summary`,
        `1–2 sentence overview of what this skill does.`,
        ``,
        `## Repeated Instructions`,
        `Rules or phrases stated more than once. Quote each instance and its line region.`,
        ``,
        `## Verbose Passages`,
        `Paragraphs that could be compressed without losing meaning. Quote and suggest a shorter form.`,
        ``,
        `## Token Estimate`,
        `Rough token cost per invocation. Identify the top 3 highest-cost passages and whether`,
        `they justify their cost given the task complexity.`,
        ``,
        `## Suggested Cuts`,
        `Specific text to remove or merge, ranked by token savings. 1–2 sentences each.`,
      ],
    ),
  },
]
