import { SPLIT_PROMPT_TEMPLATE, ANALYZE_PROMPT_TEMPLATE } from '../../Editor/commentUtils'
import type { PromptPreset } from '../../shared/PromptActionConfig/presetTypes'

export const SPLIT_PRESETS: PromptPreset[] = [
  {
    name: '',
    label: 'Restructure into sections',
    hint: 'default · group into ## cells',
    prompt: SPLIT_PROMPT_TEMPLATE,
  },
  {
    name: 'cells',
    label: 'Split into fine cells',
    hint: 'finer per-topic cells',
    prompt: [
      `You are splitting a Pathly skill file into fine-grained, per-topic cells.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Identify every distinct topic, rule, or instruction and give each its own ## section.`,
      `Aim for cells of 3–10 lines each — small enough to edit independently in the skill editor.`,
      ``,
      `Rules:`,
      `- Preserve all existing content exactly — do not rewrite, add, or remove instructions`,
      `- Preserve every character byte-for-byte, including Unicode punctuation (em-dash —, en-dash –,`,
      `  curly quotes ' ' " ", ellipsis …). Never substitute or re-encode them.`,
      `- Every ## heading must be unique and 3–6 words`,
      `- Maintain the original logical order`,
      ``,
      `Write the restructured content to: {{FILE}}.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'tighten',
    label: 'Condense prose',
    hint: 'tighten without losing meaning',
    prompt: [
      `You are condensing a Pathly skill file to reduce verbosity without losing any meaning.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Rewrite each paragraph or rule to be as concise as possible. Remove filler words, merge`,
      `redundant sentences, and shorten examples — but never drop a distinct instruction or constraint.`,
      ``,
      `Rules:`,
      `- Every original instruction or constraint must survive — compress, do not delete`,
      `- Preserve every character byte-for-byte in headings and code blocks`,
      `- Preserve Unicode punctuation (em-dash —, en-dash –, curly quotes ' ' " ", ellipsis …).`,
      `  Never substitute or re-encode them.`,
      `- Keep the existing ## structure; do not add or remove sections`,
      ``,
      `Write the condensed content to: {{FILE}}.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'headings',
    label: 'Normalize headings',
    hint: 'normalize heading hierarchy',
    prompt: [
      `You are normalizing the heading hierarchy of a Pathly skill file.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Ensure the file uses a consistent ## / ### heading hierarchy:`,
      `- Top-level sections use ## (H2)`,
      `- Sub-sections use ### (H3); avoid H4+ unless strictly necessary`,
      `- Headings are title-cased and 3–6 words`,
      `- Duplicate headings are disambiguated with a suffix`,
      ``,
      `Rules:`,
      `- Preserve all body text exactly — only heading levels and wording may change`,
      `- Preserve every character byte-for-byte in body text, including Unicode punctuation`,
      `  (em-dash —, en-dash –, curly quotes ' ' " ", ellipsis …). Never substitute or re-encode them.`,
      `- Maintain the original logical order`,
      ``,
      `Write the normalized content to: {{FILE}}.draft`,
      `Write the file as UTF-8 using your native file-writing tool. Do NOT route content through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection) — on Windows PowerShell they corrupt`,
      `Unicode into mojibake (— becomes "â€").`,
      ``,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
]

export const ANALYZE_LENSES: PromptPreset[] = [
  {
    name: '',
    label: 'Full quality review',
    hint: 'default · strengths, gaps, redundancy',
    prompt: ANALYZE_PROMPT_TEMPLATE,
  },
  {
    name: 'clarity',
    label: 'Clarity audit',
    hint: 'ambiguity / misread risks',
    prompt: [
      `You are auditing a Pathly skill file for clarity and misread risks.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Write a clarity report to: {{FILE}}.analysis`,
      ``,
      `Format your report as markdown with these sections:`,
      ``,
      `## Summary`,
      `1–2 sentence overview of what this skill does.`,
      ``,
      `## Ambiguous Instructions`,
      `Phrases or rules that an agent could misinterpret. Quote the exact text and explain the risk.`,
      ``,
      `## Implicit Assumptions`,
      `Things the skill assumes without stating — prior knowledge, context, or tool availability.`,
      ``,
      `## Suggested Rewrites`,
      `Concrete, drop-in rewrites for the most ambiguous passages. 1–2 per finding.`,
      ``,
      `Write the report as UTF-8 using your native file-writing tool — do NOT route it through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection), which corrupt Unicode on Windows.`,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'gaps',
    label: 'Completeness check',
    hint: 'completeness / missing edge cases',
    prompt: [
      `You are checking a Pathly skill file for completeness and missing edge cases.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Write a completeness report to: {{FILE}}.analysis`,
      ``,
      `Format your report as markdown with these sections:`,
      ``,
      `## Summary`,
      `1–2 sentence overview of what this skill does.`,
      ``,
      `## Missing Edge Cases`,
      `Scenarios the skill does not handle. For each: describe the scenario and its likely impact.`,
      ``,
      `## Incomplete Instructions`,
      `Steps that are started but not fully specified — an agent would need to guess.`,
      `Reference exact phrases or sections where possible.`,
      ``,
      `## Suggested Additions`,
      `Concrete text or rules to add, ranked by impact. Keep each suggestion to 1–3 sentences.`,
      ``,
      `Write the report as UTF-8 using your native file-writing tool — do NOT route it through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection), which corrupt Unicode on Windows.`,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
  {
    name: 'redundancy',
    label: 'Redundancy scan',
    hint: 'verbosity + token cost',
    prompt: [
      `You are scanning a Pathly skill file for redundancy and token waste.`,
      ``,
      `Read the file at: {{FILE}}`,
      ``,
      `Write a redundancy report to: {{FILE}}.analysis`,
      ``,
      `Format your report as markdown with these sections:`,
      ``,
      `## Summary`,
      `1–2 sentence overview of what this skill does.`,
      ``,
      `## Repeated Instructions`,
      `Rules or phrases stated more than once. Quote each instance and its line region.`,
      ``,
      `## Verbose Passages`,
      `Paragraphs that could be compressed without losing meaning. Quote and suggest a shorter form.`,
      ``,
      `## Token Estimate`,
      `Rough token cost per invocation. Identify the top 3 highest-cost passages and whether`,
      `they justify their cost given the task complexity.`,
      ``,
      `## Suggested Cuts`,
      `Specific text to remove or merge, ranked by token savings. 1–2 sentences each.`,
      ``,
      `Write the report as UTF-8 using your native file-writing tool — do NOT route it through shell`,
      `commands (Get-Content/Set-Content/Out-File or > redirection), which corrupt Unicode on Windows.`,
      `Do not write anything else. Exit when done.`,
    ].join('\n'),
  },
]
