#!/usr/bin/env python3
"""Generate an INDEX.md for every domain folder under tests/.

Each test file's one-line description is derived from its own source — the module
docstring's first line if present, otherwise a summary synthesised from its test
function names — so the index is generated from the real code and cannot drift into
a lie. The per-folder *purpose* line (FOLDER_PURPOSE below) is the only hand-curated
part; add a new folder there when you create one.

Usage:
    python scripts/gen_test_index.py          # (re)write all INDEX.md files
    python scripts/gen_test_index.py --check   # exit 1 if any INDEX.md is stale

Wire `--check` into CI to keep the indexes honest as tests are added or moved.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent.parent / "tests"

# The one hand-curated line per folder. Keep in sync when adding a domain folder.
FOLDER_PURPOSE: dict[str, str] = {
    "comms_board": "Comms board / message-board subsystem — messages, tasks, artifacts, "
    "goals, context retrieval & relevance, board mirror & hydration.",
    "fsm_flows": "FSM engine, gates, transitions, flow definitions, feedback protocol "
    "& fix-routing.",
    "runner_supervisor": "Runner control loop, supervisor, spawn channel, lane/worktree "
    "isolation, file-claim registry, services facade.",
    "telemetry": "Cost/token telemetry — invocation projection, pricing, OTel export, "
    "observability, log formatting.",
    "install_skills": "Adapter install/setup, stitch & compose, skill composition / "
    "round-trip / export, plugin manifests.",
    "storage_paths": "Feature/goal storage layout, slugs, canonical artifact paths, "
    "storage migrations.",
    "code_intel": "Code-intelligence query proxy — graph reindex, path resolve, LSP "
    "session, query gate & logging.",
    "dag_goals": "Goal/DAG decomposition & scheduling — feature/flow/project decompose, "
    "goals read-model, PRD import.",
    "db": "Database layer — schema/queries, connection isolation, write guard.",
    "http_api": "HTTP server surface — Flask app & endpoints, chat handler, "
    "Settings.from_env, prompt-event contract.",
}

_ACRONYMS = {"db": "DB", "http": "HTTP", "api": "API", "fsm": "FSM", "dag": "DAG", "lsp": "LSP"}

_GENERATED_NOTE = (
    "<!-- Generated by scripts/gen_test_index.py — do not edit by hand. "
    "Rerun `python scripts/gen_test_index.py` to refresh. -->"
)


def _title(folder: str) -> str:
    return " ".join(_ACRONYMS.get(w, w.capitalize()) for w in folder.split("_"))


def _humanize(test_name: str) -> str:
    return test_name.removeprefix("test_").replace("_", " ").strip()


def _iter_test_names(tree: ast.Module) -> list[str]:
    """Top-level `test_*` functions plus `test_*` methods inside `Test*` classes."""
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
            "test_"
        ):
            names.append(node.name)
        elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
            for sub in node.body:
                if isinstance(
                    sub, (ast.FunctionDef, ast.AsyncFunctionDef)
                ) and sub.name.startswith("test_"):
                    names.append(sub.name)
    return names


def _describe(path: Path) -> tuple[str, int]:
    """Return (description, test_count) for a test file, derived from its source."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names = _iter_test_names(tree)
    doc = ast.get_docstring(tree)
    if doc:
        first = next((ln.strip() for ln in doc.splitlines() if ln.strip()), "")
        desc = first.rstrip(".")
    else:
        shown = "; ".join(_humanize(n) for n in names[:3])
        if len(names) > 3:
            shown += "; …"
        desc = f"covers {shown}" if shown else "(no docstring; no test_* functions found)"
    return desc, len(names)


def _render(folder: str, files: list[Path]) -> str:
    lines = [
        _GENERATED_NOTE,
        "",
        f"# {_title(folder)} tests",
        "",
        FOLDER_PURPOSE.get(folder, "_(no purpose registered — add one in scripts/gen_test_index.py)_"),
        "",
        f"{len(files)} test file(s).",
        "",
        "| File | Covers | Tests |",
        "| --- | --- | --- |",
    ]
    for path in sorted(files, key=lambda p: p.name):
        desc, count = _describe(path)
        lines.append(f"| `{path.name}` | {desc} | {count} |")
    lines.append("")
    return "\n".join(lines)


def _render_root(folders: list[str], counts: dict[str, int]) -> str:
    lines = [
        _GENERATED_NOTE,
        "",
        "# Test suite index",
        "",
        "Tests are grouped into domain folders that mirror the app's architecture "
        "layers. Each folder has its own `INDEX.md` with a per-file breakdown. Shared "
        "path anchors live in `tests/_paths.py`; fixtures in `tests/conftest.py`.",
        "",
        "| Folder | Purpose | Files |",
        "| --- | --- | --- |",
    ]
    for folder in folders:
        lines.append(
            f"| [`{folder}/`]({folder}/INDEX.md) | {FOLDER_PURPOSE.get(folder, '')} | {counts[folder]} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any INDEX.md is stale")
    args = ap.parse_args()

    folders = sorted(
        p.name
        for p in TESTS_DIR.iterdir()
        if p.is_dir() and p.name not in {"snapshots", "__pycache__"}
    )
    counts: dict[str, int] = {}
    outputs: dict[Path, str] = {}
    for folder in folders:
        fdir = TESTS_DIR / folder
        files = [p for p in fdir.glob("test_*.py")]
        counts[folder] = len(files)
        outputs[fdir / "INDEX.md"] = _render(folder, files)
    outputs[TESTS_DIR / "INDEX.md"] = _render_root(folders, counts)

    stale: list[Path] = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale test INDEX.md files (run scripts/gen_test_index.py):")
            for p in stale:
                print(f"  {p.relative_to(TESTS_DIR.parent)}")
            return 1
        print("All test INDEX.md files up to date.")
        return 0

    print(f"Wrote {len(outputs)} INDEX.md files across {len(folders)} folders.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
