#!/usr/bin/env python3
"""Generate studio/src/renderer/src/lib/adapters.gen.ts from core/adapters.yaml.

Run this script whenever adapters.yaml changes. The generated file is the
single TS source of adapter metadata — never hand-edit it.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
ADAPTERS_YAML = ROOT / "src" / "pathly_data" / "core" / "adapters.yaml"
OUT_TS = ROOT / "studio" / "src" / "renderer" / "src" / "lib" / "adapters.gen.ts"

_COLOR_HINTS: dict[str, str] = {
    "claude": "#D97706",
    "codex": "#2563EB",
    "copilot": "#7C3AED",
}


def generate(adapters: dict) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/gen_adapters_ts.py — do not edit.",
        "// Source of truth: src/pathly_data/core/adapters.yaml",
        "",
        "export interface AdapterMeta {",
        "  terminalKind: string;",
        "  supportsResume: boolean;",
        "  headless: boolean;",
        "  color: string;",
        "}",
        "",
        "export const ADAPTERS: Record<string, AdapterMeta> = {",
    ]
    for name, cfg in adapters.items():
        supports_resume = cfg.get("resume") is not None
        has_headless = cfg.get("headless") is not None
        color = _COLOR_HINTS.get(name, "#6B7280")
        lines.append(f'  "{name}": {{')
        lines.append(f'    terminalKind: "{cfg.get("terminal_kind", name)}",')
        lines.append(f"    supportsResume: {str(supports_resume).lower()},")
        lines.append(f"    headless: {str(has_headless).lower()},")
        lines.append(f'    color: "{color}",')
        lines.append("  },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not ADAPTERS_YAML.exists():
        print(f"ERROR: {ADAPTERS_YAML} not found", file=sys.stderr)
        sys.exit(1)

    if not OUT_TS.parent.exists():
        print(f"ERROR: output directory {OUT_TS.parent} does not exist", file=sys.stderr)
        sys.exit(1)

    adapters = yaml.safe_load(ADAPTERS_YAML.read_text(encoding="utf-8"))
    content = generate(adapters)
    OUT_TS.write_text(content, encoding="utf-8")
    print(f"Written: {OUT_TS}")


if __name__ == "__main__":
    main()
