// AUTO-GENERATED by scripts/gen_adapters_ts.py — do not edit.
// Source of truth: src/pathly_data/core/adapters.yaml

export interface AdapterMeta {
  terminalKind: string;
  supportsResume: boolean;
  headless: boolean;
  color: string;
}

export const ADAPTERS: Record<string, AdapterMeta> = {
  "claude": {
    terminalKind: "claude",
    supportsResume: true,
    headless: true,
    color: "#D97706",
  },
  "codex": {
    terminalKind: "codex",
    supportsResume: true,
    headless: true,
    color: "#2563EB",
  },
  "copilot": {
    terminalKind: "shell",
    supportsResume: false,
    headless: false,
    color: "#7C3AED",
  },
  "antigravity": {
    terminalKind: "shell",
    supportsResume: false,
    headless: false,
    color: "#6B7280",
  },
};
