// AUTO-GENERATED by scripts/gen_adapters_ts.py — do not edit.
// Source of truth: src/pathly_data/core/adapters.yaml

export type CliAdapter = "claude" | "codex" | "copilot" | "antigravity";

export interface AdapterMeta {
  label: string;
  hint: string;
  terminalKind: string;
  supportsResume: boolean;
  headless: boolean;
  color: string;
}

export const ADAPTERS: Record<string, AdapterMeta> = {
  "claude": {
    label: "Claude",
    hint: "Claude Code",
    terminalKind: "claude",
    supportsResume: true,
    headless: true,
    color: "#D97706",
  },
  "codex": {
    label: "Codex",
    hint: "OpenAI Codex",
    terminalKind: "codex",
    supportsResume: true,
    headless: true,
    color: "#2563EB",
  },
  "copilot": {
    label: "Copilot",
    hint: "GitHub Copilot",
    terminalKind: "shell",
    supportsResume: false,
    headless: false,
    color: "#7C3AED",
  },
  "antigravity": {
    label: "Gemini",
    hint: "Antigravity CLI",
    terminalKind: "antigravity",
    supportsResume: false,
    headless: true,
    color: "#16A34A",
  },
};
